### ISSUE TITLE
Bad practice in calling subscript

### ISSUE THREAD

**Issue by kcp2p** [42-Bangkok/scripts#4]
https://github.com/42-Bangkok/scripts/blob/43551669bb4e8731ed24803e53f351ddf34f2954/app/main.py#L24

Should use function calling or importing the module, python executable is different on other distributions.

**Comment by Lodimup** [comment]
It is designed to be run containerized. Correct distro will always be used. 

Placing a script in the same dir as main.py will be discovered and usable w/o changing main.

**Comment by kcp2p** [comment]
Got it.
